<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>To-Do App</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="shortcut icon" href="img/favicon.png" type="image/x-icon">
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link href='/css/style.css' rel='stylesheet' type='text/css'>
        <script type="text/javascript" src="index.js" defer></script>
    </head>
    <body id="body">
    <h1 class="headline">Crypto News</h1>
    <div id="content" class="content">
    </div>

    </div>
    </body>
</html>
